package com.penfit.penfit.global.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

public enum OptionCode {

    KEEP,
    REDUCE_HALF,
    PAUSE_UNTIL_REEMPLOYED,
    STOP_AND_REPLAN,
    CLOSE_ACCOUNT,
    CUT_EXPENSE_AND_KEEP,
    PAUSE_TEMPORARILY,
    DELAY_EVENT,
    REDUCE_EVENT_COST_AND_KEEP,
    REDUCE_CONTRIBUTION,
    PAUSE_UNTIL_EVENT,
    CHOOSE_ALTERNATIVE_AND_KEEP,
    REDUCE_TO_MINIMUM,
    PAUSE_SIX_MONTHS,
    REBALANCE,
    INCREASE_SAFE_ASSET,
    PAUSE_CONTRIBUTION,
    SELL_OR_CLOSE,
    INCREASE_CONTRIBUTION
}
