CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_id        VARCHAR(50)  NOT NULL,
    nickname        VARCHAR(30)  NOT NULL,
    email           VARCHAR(255),
    email_consent   BOOLEAN      NOT NULL DEFAULT FALSE,
    is_demo         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uk_users_kakao_id UNIQUE (kakao_id),
    CONSTRAINT ck_users_email_consent CHECK (email_consent = FALSE OR email IS NOT NULL)
);

CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    token       VARCHAR(512) NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_refresh_tokens_user UNIQUE (user_id)
);
CREATE INDEX ix_refresh_tokens_token ON refresh_tokens (token);

CREATE TABLE financial_profiles (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT      NOT NULL,
    age_band             VARCHAR(20) NOT NULL,
    occupation_type      VARCHAR(30) NOT NULL,
    monthly_salary       BIGINT      NOT NULL,
    living_expense_band  VARCHAR(30) NOT NULL,
    asset_band           VARCHAR(30) NOT NULL,
    debt_band            VARCHAR(30) NOT NULL,
    emergency_fund_band  VARCHAR(30) NOT NULL,
    monthly_savings      BIGINT      NOT NULL,
    current_investment   BIGINT      NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_financial_profiles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_financial_profiles_user UNIQUE (user_id),
    CONSTRAINT ck_financial_profiles_age_band CHECK (age_band IN
        ('AGE_23_25', 'AGE_26_28', 'AGE_29_31', 'AGE_32_34')),
    CONSTRAINT ck_financial_profiles_occupation CHECK (occupation_type IN
        ('REGULAR_EMPLOYEE', 'CONTRACT_EMPLOYEE', 'FREELANCER', 'SELF_EMPLOYED',
         'PUBLIC_OFFICIAL', 'UNEMPLOYED', 'OTHER')),
    CONSTRAINT ck_financial_profiles_living CHECK (living_expense_band IN
        ('LIVING_LE_1M', 'LIVING_GT_1M_LE_1_5M', 'LIVING_GT_1_5M_LE_2M', 'LIVING_GT_2M')),
    CONSTRAINT ck_financial_profiles_asset CHECK (asset_band IN
        ('ASSET_LT_10M', 'ASSET_10M_30M', 'ASSET_30M_50M', 'ASSET_GE_50M')),
    CONSTRAINT ck_financial_profiles_debt CHECK (debt_band IN
        ('DEBT_NONE', 'DEBT_LT_10M', 'DEBT_10M_30M', 'DEBT_GE_30M')),
    CONSTRAINT ck_financial_profiles_emergency CHECK (emergency_fund_band IN
        ('EMERGENCY_LT_1M', 'EMERGENCY_1M_3M', 'EMERGENCY_3M_5M', 'EMERGENCY_GE_5M')),
    CONSTRAINT ck_financial_profiles_amounts CHECK (
        monthly_salary >= 0 AND monthly_savings >= 0 AND current_investment >= 0)
);

CREATE TABLE pension_setups (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT        NOT NULL,
    account_type          VARCHAR(30)   NOT NULL,
    monthly_contribution  BIGINT        NOT NULL,
    preview_future_asset  BIGINT        NOT NULL,
    expected_return_rate  NUMERIC(6, 4) NOT NULL DEFAULT 0.0500,
    contribution_years    INT           NOT NULL DEFAULT 30,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_pension_setups_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_pension_setups_user UNIQUE (user_id),
    CONSTRAINT ck_pension_setups_account_type CHECK (account_type IN
        ('PENSION_SAVINGS_FUND', 'INDIVIDUAL_IRP', 'PENSION_SAVINGS_INSURANCE')),
    CONSTRAINT ck_pension_setups_contribution CHECK (monthly_contribution >= 50000),
    CONSTRAINT ck_pension_setups_years CHECK (contribution_years > 0)
);

CREATE TABLE rehearsal_scenarios (
    scenario_code          VARCHAR(30) NOT NULL,
    display_order          INT         NOT NULL,
    title                  VARCHAR(50) NOT NULL,
    badge                  VARCHAR(60),
    situation              TEXT        NOT NULL,
    question               TEXT        NOT NULL,
    baseline_contribution  BIGINT,
    context_cards          JSONB       NOT NULL DEFAULT '[]'::jsonb,
    irp_notice             TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_rehearsal_scenarios PRIMARY KEY (scenario_code),
    CONSTRAINT uk_rehearsal_scenarios_order UNIQUE (display_order),
    CONSTRAINT ck_rehearsal_scenarios_code CHECK (scenario_code IN
        ('JOB_CHANGE', 'INDEPENDENCE', 'MARRIAGE', 'HOME_PURCHASE', 'CHILDBIRTH', 'MARKET_DOWNTURN'))
);

CREATE TABLE rehearsal_scenario_options (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_code  VARCHAR(30) NOT NULL,
    option_code    VARCHAR(50) NOT NULL,
    display_order  INT         NOT NULL,
    title          TEXT        NOT NULL,
    description    TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_scenario_options_scenario FOREIGN KEY (scenario_code)
        REFERENCES rehearsal_scenarios (scenario_code) ON DELETE CASCADE,
    CONSTRAINT uk_scenario_options UNIQUE (scenario_code, option_code),
    CONSTRAINT uk_scenario_options_order UNIQUE (scenario_code, display_order),
    CONSTRAINT ck_scenario_options_code CHECK (option_code IN
        ('KEEP', 'REDUCE_HALF', 'PAUSE_UNTIL_REEMPLOYED', 'STOP_AND_REPLAN', 'CLOSE_ACCOUNT',
         'CUT_EXPENSE_AND_KEEP', 'PAUSE_TEMPORARILY', 'DELAY_EVENT', 'REDUCE_EVENT_COST_AND_KEEP',
         'REDUCE_CONTRIBUTION', 'PAUSE_UNTIL_EVENT', 'CHOOSE_ALTERNATIVE_AND_KEEP',
         'REDUCE_TO_MINIMUM', 'PAUSE_SIX_MONTHS', 'REBALANCE', 'INCREASE_SAFE_ASSET',
         'PAUSE_CONTRIBUTION', 'SELL_OR_CLOSE', 'INCREASE_CONTRIBUTION'))
);

CREATE TABLE rehearsals (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT      NOT NULL,
    status                VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    preview_future_asset  BIGINT      NOT NULL,
    retry_count           INT         NOT NULL DEFAULT 0,
    failure_code          VARCHAR(40),
    failure_message       TEXT,
    completed_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_rehearsals_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_rehearsals_status CHECK (status IN
        ('IN_PROGRESS', 'ANALYZING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_rehearsals_retry_count CHECK (retry_count >= 0)
);
CREATE INDEX ix_rehearsals_user ON rehearsals (user_id, created_at DESC);

CREATE TABLE rehearsal_answers (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rehearsal_id   BIGINT      NOT NULL,
    scenario_code  VARCHAR(30) NOT NULL,
    option_code    VARCHAR(50) NOT NULL,
    answered_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_rehearsal_answers_rehearsal FOREIGN KEY (rehearsal_id)
        REFERENCES rehearsals (id) ON DELETE CASCADE,
    CONSTRAINT fk_rehearsal_answers_option FOREIGN KEY (scenario_code, option_code)
        REFERENCES rehearsal_scenario_options (scenario_code, option_code),
    CONSTRAINT uk_rehearsal_answers UNIQUE (rehearsal_id, scenario_code)
);

CREATE TABLE pension_passports (
    id                               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                          BIGINT      NOT NULL,
    rehearsal_id                     BIGINT      NOT NULL,
    type_code                        VARCHAR(40) NOT NULL,
    sustainable_monthly_contribution BIGINT      NOT NULL,
    biggest_interruption_risk_code   VARCHAR(30) NOT NULL,
    market_risk_level                VARCHAR(10) NOT NULL,
    summary                          TEXT        NOT NULL,
    judgment_reason                  TEXT        NOT NULL,
    ai_raw_response                  JSONB       NOT NULL,
    model_version                    VARCHAR(50) NOT NULL,
    created_at                       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_passports_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_passports_rehearsal FOREIGN KEY (rehearsal_id) REFERENCES rehearsals (id) ON DELETE CASCADE,
    CONSTRAINT uk_passports_user UNIQUE (user_id),
    CONSTRAINT ck_passports_type_code CHECK (type_code IN
        ('STEADY_PIONEER', 'FLEXIBLE_BALANCER', 'CAUTIOUS_GUARDIAN', 'REALISTIC_PLANNER')),
    CONSTRAINT ck_passports_risk_code CHECK (biggest_interruption_risk_code IN
        ('JOB_CHANGE', 'INDEPENDENCE', 'MARRIAGE', 'HOME_PURCHASE', 'CHILDBIRTH', 'MARKET_DOWNTURN')),
    CONSTRAINT ck_passports_market_risk CHECK (market_risk_level IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_passports_sustainable CHECK (sustainable_monthly_contribution >= 0)
);

CREATE TABLE passport_detailed_analyses (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passport_id           BIGINT      NOT NULL,
    scenario_code         VARCHAR(30) NOT NULL,
    selected_option_code  VARCHAR(50) NOT NULL,
    display_order         INT         NOT NULL,
    behavior_summary      TEXT        NOT NULL,
    interpretation        TEXT        NOT NULL,
    CONSTRAINT fk_detailed_analyses_passport FOREIGN KEY (passport_id)
        REFERENCES pension_passports (id) ON DELETE CASCADE,
    CONSTRAINT fk_detailed_analyses_option FOREIGN KEY (scenario_code, selected_option_code)
        REFERENCES rehearsal_scenario_options (scenario_code, option_code),
    CONSTRAINT uk_detailed_analyses UNIQUE (passport_id, scenario_code)
);

CREATE TABLE pension_plans (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT        NOT NULL,
    passport_id            BIGINT        NOT NULL,
    plan_name              VARCHAR(50)   NOT NULL,
    account_type           VARCHAR(30)   NOT NULL,
    monthly_contribution   BIGINT        NOT NULL,
    stock_ratio            NUMERIC(5, 2) NOT NULL,
    bond_ratio             NUMERIC(5, 2) NOT NULL,
    deposit_ratio          NUMERIC(5, 2) NOT NULL,
    recommendation_reason  TEXT          NOT NULL,
    expected_future_asset  BIGINT        NOT NULL,
    contribution_years     INT           NOT NULL DEFAULT 30,
    expected_return_rate   NUMERIC(6, 4) NOT NULL DEFAULT 0.0500,
    ai_raw_response        JSONB         NOT NULL,
    model_version          VARCHAR(50)   NOT NULL,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_pension_plans_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_pension_plans_passport FOREIGN KEY (passport_id)
        REFERENCES pension_passports (id) ON DELETE CASCADE,
    CONSTRAINT uk_pension_plans_user UNIQUE (user_id),
    CONSTRAINT ck_pension_plans_account_type CHECK (account_type IN
        ('PENSION_SAVINGS_FUND', 'INDIVIDUAL_IRP', 'PENSION_SAVINGS_INSURANCE')),
    CONSTRAINT ck_pension_plans_contribution CHECK (monthly_contribution > 0),
    CONSTRAINT ck_pension_plans_ratio_range CHECK (
        stock_ratio BETWEEN 0 AND 100 AND bond_ratio BETWEEN 0 AND 100 AND deposit_ratio BETWEEN 0 AND 100),
    CONSTRAINT ck_pension_plans_ratio_sum CHECK (stock_ratio + bond_ratio + deposit_ratio = 100)
);

CREATE TABLE pension_plan_advantages (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id        BIGINT NOT NULL,
    display_order  INT    NOT NULL,
    content        TEXT   NOT NULL,
    CONSTRAINT fk_plan_advantages_plan FOREIGN KEY (plan_id) REFERENCES pension_plans (id) ON DELETE CASCADE,
    CONSTRAINT uk_plan_advantages UNIQUE (plan_id, display_order)
);

CREATE TABLE pension_products (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_type     VARCHAR(20)   NOT NULL,
    provider_name     VARCHAR(50)   NOT NULL,
    product_name      VARCHAR(100)  NOT NULL,
    account_type      VARCHAR(30)   NOT NULL,
    product_type      VARCHAR(30)   NOT NULL,
    summary           TEXT          NOT NULL,
    fee_min_rate      NUMERIC(6, 4) NOT NULL,
    fee_max_rate      NUMERIC(6, 4) NOT NULL,
    investment_scope  VARCHAR(100)  NOT NULL,
    official_url      VARCHAR(500)  NOT NULL,
    is_active         BOOLEAN       NOT NULL DEFAULT TRUE,
    data_source       VARCHAR(100)  NOT NULL,
    reference_date    DATE          NOT NULL,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uk_pension_products_name UNIQUE (provider_name, product_name),
    CONSTRAINT ck_pension_products_provider_type CHECK (provider_type IN ('BANK', 'SECURITIES', 'INSURANCE')),
    CONSTRAINT ck_pension_products_account_type CHECK (account_type IN
        ('PENSION_SAVINGS_FUND', 'INDIVIDUAL_IRP', 'PENSION_SAVINGS_INSURANCE')),
    CONSTRAINT ck_pension_products_product_type CHECK (product_type IN
        ('FUND_ACCOUNT', 'IRP_ACCOUNT', 'INSURANCE_PRODUCT')),
    CONSTRAINT ck_pension_products_type_mapping CHECK (
        (product_type = 'FUND_ACCOUNT' AND account_type = 'PENSION_SAVINGS_FUND') OR
        (product_type = 'IRP_ACCOUNT' AND account_type = 'INDIVIDUAL_IRP') OR
        (product_type = 'INSURANCE_PRODUCT' AND account_type = 'PENSION_SAVINGS_INSURANCE')),
    CONSTRAINT ck_pension_products_fee CHECK (fee_min_rate >= 0 AND fee_max_rate >= fee_min_rate)
);
CREATE INDEX ix_pension_products_account_type ON pension_products (account_type, is_active);

CREATE TABLE product_features (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT NOT NULL,
    display_order  INT    NOT NULL,
    content        TEXT   NOT NULL,
    CONSTRAINT fk_product_features_product FOREIGN KEY (product_id)
        REFERENCES pension_products (id) ON DELETE CASCADE,
    CONSTRAINT uk_product_features UNIQUE (product_id, display_order)
);

CREATE TABLE product_cautions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     BIGINT NOT NULL,
    display_order  INT    NOT NULL,
    content        TEXT   NOT NULL,
    CONSTRAINT fk_product_cautions_product FOREIGN KEY (product_id)
        REFERENCES pension_products (id) ON DELETE CASCADE,
    CONSTRAINT uk_product_cautions UNIQUE (product_id, display_order)
);

CREATE TABLE product_recommendations (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT        NOT NULL,
    plan_id                BIGINT        NOT NULL,
    product_id             BIGINT        NOT NULL,
    rank                   INT           NOT NULL,
    fit_score              NUMERIC(6, 4) NOT NULL,
    fit_level              VARCHAR(20)   NOT NULL,
    recommendation_reason  TEXT          NOT NULL,
    model_version          VARCHAR(50)   NOT NULL,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT fk_recommendations_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_recommendations_plan FOREIGN KEY (plan_id) REFERENCES pension_plans (id) ON DELETE CASCADE,
    CONSTRAINT fk_recommendations_product FOREIGN KEY (product_id) REFERENCES pension_products (id),
    CONSTRAINT uk_recommendations_rank UNIQUE (user_id, rank),
    CONSTRAINT uk_recommendations_product UNIQUE (user_id, product_id),
    CONSTRAINT ck_recommendations_rank CHECK (rank BETWEEN 1 AND 3),
    CONSTRAINT ck_recommendations_fit_score CHECK (fit_score BETWEEN 0 AND 1),
    CONSTRAINT ck_recommendations_fit_level CHECK (fit_level IN ('VERY_HIGH', 'HIGH', 'MEDIUM', 'LOW'))
);

CREATE TABLE saved_products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL,
    product_id  BIGINT      NOT NULL,
    saved_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_saved_products_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_products_product FOREIGN KEY (product_id) REFERENCES pension_products (id) ON DELETE CASCADE,
    CONSTRAINT uk_saved_products UNIQUE (user_id, product_id)
);

CREATE TABLE virtual_transactions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_code  VARCHAR(30) NOT NULL,
    merchant_name  VARCHAR(100) NOT NULL,
    amount         BIGINT      NOT NULL,
    transacted_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT ck_virtual_transactions_category CHECK (category_code IN
        ('FOOD_DELIVERY', 'SHOPPING', 'TRANSPORTATION', 'SUBSCRIPTION', 'OTHER')),
    CONSTRAINT ck_virtual_transactions_amount CHECK (amount > 0)
);
CREATE INDEX ix_virtual_transactions_date ON virtual_transactions (transacted_at);

CREATE TABLE spending_analyses (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT      NOT NULL,
    analysis_start_date  DATE        NOT NULL,
    analysis_end_date    DATE        NOT NULL,
    top_category_code    VARCHAR(30) NOT NULL,
    recurring_expense    BIGINT      NOT NULL,
    reducible_amount     BIGINT      NOT NULL,
    summary              TEXT        NOT NULL,
    ai_raw_response      JSONB       NOT NULL,
    model_version        VARCHAR(50) NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_spending_analyses_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_spending_analyses_period CHECK (analysis_start_date <= analysis_end_date),
    CONSTRAINT ck_spending_analyses_top_category CHECK (top_category_code IN
        ('FOOD_DELIVERY', 'SHOPPING', 'TRANSPORTATION', 'SUBSCRIPTION', 'OTHER')),
    CONSTRAINT ck_spending_analyses_amounts CHECK (recurring_expense >= 0 AND reducible_amount >= 0)
);
CREATE INDEX ix_spending_analyses_user ON spending_analyses (user_id, created_at DESC);

CREATE TABLE spending_category_amounts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id    BIGINT        NOT NULL,
    category_code  VARCHAR(30)   NOT NULL,
    amount         BIGINT        NOT NULL,
    ratio          NUMERIC(5, 2) NOT NULL,
    display_order  INT           NOT NULL,
    CONSTRAINT fk_category_amounts_analysis FOREIGN KEY (analysis_id)
        REFERENCES spending_analyses (id) ON DELETE CASCADE,
    CONSTRAINT uk_category_amounts UNIQUE (analysis_id, category_code),
    CONSTRAINT ck_category_amounts_category CHECK (category_code IN
        ('FOOD_DELIVERY', 'SHOPPING', 'TRANSPORTATION', 'SUBSCRIPTION', 'OTHER')),
    CONSTRAINT ck_category_amounts_ratio CHECK (ratio BETWEEN 0 AND 100)
);

CREATE TABLE spending_key_insights (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id    BIGINT NOT NULL,
    display_order  INT    NOT NULL,
    content        TEXT   NOT NULL,
    CONSTRAINT fk_key_insights_analysis FOREIGN KEY (analysis_id)
        REFERENCES spending_analyses (id) ON DELETE CASCADE,
    CONSTRAINT uk_key_insights UNIQUE (analysis_id, display_order),
    CONSTRAINT ck_key_insights_order CHECK (display_order BETWEEN 1 AND 3)
);

CREATE TABLE behavior_missions (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                BIGINT      NOT NULL,
    spending_analysis_id   BIGINT      NOT NULL,
    title                  VARCHAR(100) NOT NULL,
    description            TEXT        NOT NULL,
    reason                 TEXT        NOT NULL,
    target_amount          BIGINT      NOT NULL,
    duration_days          INT         NOT NULL DEFAULT 7,
    status                 VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    due_date               DATE        NOT NULL,
    pension_impact_amount  BIGINT,
    started_at             TIMESTAMPTZ,
    completed_at           TIMESTAMPTZ,
    model_version          VARCHAR(50) NOT NULL,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_missions_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_missions_analysis FOREIGN KEY (spending_analysis_id)
        REFERENCES spending_analyses (id) ON DELETE CASCADE,
    CONSTRAINT ck_missions_status CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'EXPIRED')),
    CONSTRAINT ck_missions_target_amount CHECK (
        target_amount BETWEEN 5000 AND 50000 AND target_amount % 5000 = 0),
    CONSTRAINT ck_missions_duration CHECK (duration_days > 0)
);

CREATE INDEX ix_missions_user_completed ON behavior_missions (user_id, completed_at);
CREATE INDEX ix_missions_user_status ON behavior_missions (user_id, status);

CREATE TABLE email_send_logs (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT       NOT NULL,
    mission_id     BIGINT,
    email          VARCHAR(255) NOT NULL,
    subject        VARCHAR(200) NOT NULL,
    status         VARCHAR(20)  NOT NULL,
    error_message  TEXT,
    sent_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT fk_email_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_email_logs_mission FOREIGN KEY (mission_id) REFERENCES behavior_missions (id) ON DELETE SET NULL,
    CONSTRAINT ck_email_logs_status CHECK (status IN ('SUCCESS', 'FAILED'))
);
CREATE INDEX ix_email_logs_user ON email_send_logs (user_id, sent_at DESC);

CREATE TABLE ai_call_logs (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT,
    api_name          VARCHAR(50) NOT NULL,
    request_id        VARCHAR(50),
    request_payload   JSONB       NOT NULL,
    response_payload  JSONB,
    http_status       INT,
    ai_error_code     VARCHAR(40),
    duration_ms       INT,
    status            VARCHAR(20) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fk_ai_call_logs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT ck_ai_call_logs_status CHECK (status IN ('SUCCESS', 'FAILED'))
);
CREATE INDEX ix_ai_call_logs_api ON ai_call_logs (api_name, created_at DESC);
CREATE INDEX ix_ai_call_logs_failed ON ai_call_logs (status, created_at DESC);
